# Generated by Django 5.2.1 on 2025-05-23 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('stocks', 'Stocks'), ('bonds', 'Bonds'), ('mutual_funds', 'Mutual Funds'), ('crypto', 'Cryptocurrencies'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_level', models.IntegerField(default=3)),
                ('avg_annual_return', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volatility', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Investment Type',
                'verbose_name_plural': 'Investment Types',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('simulated', 'Simulated')], default='active', max_length=10)),
                ('is_simulation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('investment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='investments.investmenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('split', 'Stock Split'), ('other', 'Other')], max_length=10)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strategy', models.CharField(choices=[('lump_sum', 'Lump Sum'), ('dca', 'Dollar Cost Averaging')], max_length=10)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodic_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period_months', models.IntegerField(default=1)),
                ('duration_years', models.IntegerField()),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volatility', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_simulations', to=settings.AUTH_USER_MODEL)),
                ('investment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='investments.investmenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('investment_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cumulative_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='investments.investmentsimulation')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
    ]
