# Generated by Django 5.2.1 on 2025-05-23 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Credit Factor',
                'verbose_name_plural': 'Credit Factors',
            },
        ),
        migrations.CreateModel(
            name='CreditEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missed_payments_count', models.IntegerField(default=0)),
                ('late_payments_count', models.IntegerField(default=0)),
                ('on_time_payments_streak', models.IntegerField(default=0)),
                ('total_credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_credit_usage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oldest_account_years', models.IntegerField(default=0)),
                ('average_account_age_years', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('has_credit_cards', models.BooleanField(default=False)),
                ('has_installment_loans', models.BooleanField(default=False)),
                ('has_mortgage', models.BooleanField(default=False)),
                ('has_retail_accounts', models.BooleanField(default=False)),
                ('recent_inquiries_count', models.IntegerField(default=0)),
                ('new_accounts_last_year', models.IntegerField(default=0)),
                ('estimated_score', models.IntegerField(blank=True, null=True)),
                ('confidence_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_estimations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('report_source', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit History',
                'verbose_name_plural': 'Credit Histories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CreditFactorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='credit.creditfactor')),
                ('credit_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_scores', to='credit.credithistory')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('high', 'High Impact'), ('medium', 'Medium Impact'), ('low', 'Low Impact')], max_length=10)),
                ('potential_points_gain', models.IntegerField()),
                ('timeframe_months', models.IntegerField()),
                ('credit_estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_suggestions', to='credit.creditestimation')),
            ],
            options={
                'ordering': ['-potential_points_gain'],
            },
        ),
    ]
