# Generated by Django 5.2.1 on 2025-06-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementsuggestion',
            name='implemented_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='improvementsuggestion',
            name='is_implemented',
            field=models.BooleanField(default=False),
        ),
    ]
