# Generated by Django 5.2.1 on 2025-05-23 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0001_initial'),
        ('expenses', '0001_initial'),
        ('goals', '0001_initial'),
        ('investments', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_expenses', models.BooleanField(default=True)),
                ('show_loans', models.BooleanField(default=True)),
                ('show_goals', models.BooleanField(default=True)),
                ('show_investments', models.BooleanField(default=True)),
                ('show_credit', models.BooleanField(default=True)),
                ('widget_order', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_chart_type', models.CharField(default='pie', max_length=20)),
                ('expense_time_period', models.CharField(default='month', max_length=20)),
                ('investment_chart_type', models.CharField(default='line', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('expense_summary', 'Expense Summary'), ('income_vs_expense', 'Income vs Expense'), ('savings_progress', 'Savings Progress'), ('loan_summary', 'Loan Summary'), ('investment_performance', 'Investment Performance'), ('credit_score', 'Credit Score'), ('custom', 'Custom Widget')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('size', models.CharField(default='medium', max_length=20)),
                ('refresh_interval', models.IntegerField(default=0)),
                ('custom_config', models.JSONField(blank=True, null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.dashboard')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('expense', 'Expense Insight'), ('saving', 'Saving Opportunity'), ('investment', 'Investment Tip'), ('budget', 'Budget Alert'), ('credit', 'Credit Improvement'), ('general', 'General Advice')], max_length=20)),
                ('importance_score', models.IntegerField(default=5)),
                ('is_read', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-importance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('related_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.credithistory')),
                ('related_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expense')),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.savingsgoal')),
                ('related_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.investment')),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
